[project]
name = "linecalc"
version = "0.1.0"
description = "Line calculator with currency conversions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.8",
    "requests>=2.32.5",
]
